const $=s=>document.querySelector(s), app=document.getElementById('app');
let courses=[],banks={},route={view:'home'},quiz=null;
const store={get(k,d={}){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set(k,v){localStorage.setItem(k,JSON.stringify(v))}};
const prog=id=>store.get('mb_'+id,{answers:{},correct:{},bookmarks:{},last:0});
async function init(){courses=await fetch('courses.json').then(r=>r.json());parseHash();}
window.addEventListener('hashchange',parseHash);
function parseHash(){let h=location.hash.slice(1),[v,id,mode]=h.split('/');route=h?{view:v,id,mode}:{view:'home'};render();}
function pct(c){let p=prog(c.id),n=Object.keys(p.correct).length;return Math.round(n/c.count*100);}
function shell(content){app.innerHTML=`<main class="shell">${content}</main>`;}
function home(){let total=courses.reduce((a,c)=>a+c.count,0),done=courses.reduce((a,c)=>a+Object.keys(prog(c.id).correct).length,0);shell(`<div class="top"><div class="brand"><h1>MedBank CBT</h1><p>의대 강의 기반 개인 문제은행</p></div><a class="btn soft" href="#stats">통계</a></div><section class="hero"><div><h2>오늘도 조금씩, 확실하게.</h2><p>오답과 북마크는 자동 저장돼요. iPad에서 바로 이어서 풀 수 있습니다.</p></div><div class="hero-stat">${done}<small>전체 ${total}문항 중 채점</small></div></section><div class="section-head"><h2>바이러스학</h2></div><input class="search" id="search" placeholder="과목 또는 키워드 검색"><div class="grid" id="grid">${cards(courses)}</div>`);$('#search').oninput=e=>$('#grid').innerHTML=cards(courses.filter(c=>c.title.toLowerCase().includes(e.target.value.toLowerCase())));}
function cards(cs){return cs.map(c=>{let p=pct(c),s=prog(c.id);return `<article class="course"><div class="course-icon">${c.icon}</div><h3>${c.title}</h3><div class="sub">${c.count}문항 · O/X + 5지선다</div><div class="progress"><i style="width:${p}%"></i></div><div class="tiny">진행률 ${p}%</div><div class="row"><a class="btn primary" href="#course/${c.id}">${s.last?'이어서 풀기':'시작하기'}</a></div></article>`}).join('');}
async function loadBank(id){if(!banks[id]){let c=courses.find(x=>x.id===id);banks[id]=await fetch(c.file).then(r=>r.json());}return banks[id];}
async function course(id){let c=courses.find(x=>x.id===id),q=await loadBank(id),p=prog(id),wrong=Object.values(p.correct).filter(x=>!x).length,bm=Object.keys(p.bookmarks).length;shell(`<div class="top"><div class="brand"><h1>${c.icon} ${c.title}</h1><p>${c.count}문항</p></div><a class="btn" href="#">홈</a></div><section class="panel"><div class="stats"><div class="stat"><span>진행률</span><b>${pct(c)}%</b></div><div class="stat"><span>오답</span><b>${wrong}</b></div><div class="stat"><span>북마크</span><b>${bm}</b></div></div><div class="section-head"><h2>학습 모드</h2></div><div class="row"><button class="btn primary" onclick="start('${id}','all')">전체 이어풀기</button><button class="btn soft" onclick="start('${id}','random50')">랜덤 50</button><button class="btn soft" onclick="start('${id}','wrong')">오답만</button><button class="btn soft" onclick="start('${id}','bookmark')">북마크</button></div></section>`);}
window.start=async(id,mode)=>{let all=await loadBank(id),p=prog(id),arr=[...all];if(mode==='wrong')arr=arr.filter(x=>p.correct[x.id]===false);if(mode==='bookmark')arr=arr.filter(x=>p.bookmarks[x.id]);if(mode==='random50')arr=arr.sort(()=>Math.random()-.5).slice(0,50);if(!arr.length)return alert('해당 문제를 아직 찾을 수 없어요.');let idx=mode==='all'?Math.min(p.last||0,arr.length-1):0;sessionStorage.setItem('mb_quiz',JSON.stringify({id,mode,ids:arr.map(x=>x.id),idx}));location.hash=`quiz/${id}/${mode}`;};
async function quizView(id,mode){let all=await loadBank(id),s;try{s=JSON.parse(sessionStorage.getItem('mb_quiz'));}catch{s=null;}if(!s||s.id!==id){s={id,mode,ids:all.map(x=>x.id),idx:0};}let arr=s.ids.map(x=>all.find(q=>q.id===x)).filter(Boolean);quiz={...s,arr};drawQ();}
function drawQ(){let c=courses.find(x=>x.id===quiz.id),q=quiz.arr[quiz.idx],p=prog(quiz.id),sel=p.answers[q.id],graded=q.id in p.correct,ok=p.correct[q.id],slide=Number(q.slide)||1;shell(`<div class="quiz-head"><div class="row"><a class="btn" href="#course/${quiz.id}">← 나가기</a><span class="tiny">${quiz.idx+1} / ${quiz.arr.length}</span><button class="bookmark" onclick="bookmark('${q.id}')">${p.bookmarks[q.id]?'★':'☆'}</button></div><div class="progress"><i style="width:${(quiz.idx+1)/quiz.arr.length*100}%"></i></div></div><section class="qcard"><div class="qmeta"><span>${q.type==='ox'?'O/X':'5지선다'}</span><button class="slide-link" onclick="openSlide(${slide})">📄 근거 슬라이드 ${slide} 보기</button></div><div class="qtext">${esc(q.q)}</div><div>${q.options.map((o,i)=>`<div class="option ${String(sel)===String(i)?'selected':''}" onclick="choose(${i})"><span class="num">${q.type==='ox'?esc(o):i+1}</span><span>${q.type==='ox'?'':esc(o)}</span></div>`).join('')}</div>${graded?`<div class="feedback ${ok?'good':'bad'}"><b>${ok?'정답입니다':'오답입니다'}</b><br><strong>정답:</strong> ${esc(q.options[q.answer])}<div class="explain"><strong>해설</strong><br>${esc(q.exp)}</div><button class="btn source" onclick="openSlide(${slide})">📄 슬라이드 ${slide}에서 근거 확인</button></div>`:`<button class="btn primary" style="margin-top:16px;width:100%" onclick="grade()">정답 확인</button>`}<div class="nav"><button class="btn" onclick="move(-1)" ${quiz.idx===0?'disabled':''}>이전</button><button class="btn primary" onclick="move(1)">${quiz.idx===quiz.arr.length-1?'완료':'다음'}</button></div></section>`);}
window.openSlide=page=>{let c=courses.find(x=>x.id===quiz.id);if(!c?.slideDir)return alert('연결된 강의안이 없습니다.');let url=`${c.slideDir}/${page}.jpg`;let modal=document.createElement('div');modal.className='slide-modal';modal.innerHTML=`<div class="slide-box image-viewer"><div class="slide-bar"><b>${esc(c.title)} · 슬라이드 ${page}</b><div class="row"><a class="btn soft" href="${url}" target="_blank" rel="noopener">새 탭으로 열기</a><button class="btn" id="closeSlide">닫기</button></div></div><div class="slide-stage"><img src="${url}" alt="근거 슬라이드 ${page}" loading="eager"><div class="slide-error">이미지를 불러오지 못했습니다.<br><code>${url}</code> 경로를 확인하세요.</div></div><p class="slide-help">두 손가락으로 확대하거나 이미지를 눌러 새 탭에서 크게 볼 수 있어요.</p></div>`;document.body.appendChild(modal);let img=modal.querySelector('img'),err=modal.querySelector('.slide-error');img.onerror=()=>{img.style.display='none';err.style.display='block'};img.onclick=()=>window.open(url,'_blank','noopener');modal.querySelector('#closeSlide').onclick=()=>modal.remove();modal.onclick=e=>{if(e.target===modal)modal.remove();};};
window.choose=i=>{let q=quiz.arr[quiz.idx],p=prog(quiz.id);if(q.id in p.correct)return;p.answers[q.id]=i;store.set('mb_'+quiz.id,p);drawQ();};
window.grade=()=>{let q=quiz.arr[quiz.idx],p=prog(quiz.id);if(!(q.id in p.answers))return alert('답을 선택하세요.');p.correct[q.id]=Number(p.answers[q.id])===q.answer;p.last=quiz.idx;store.set('mb_'+quiz.id,p);drawQ();};
window.move=d=>{if(quiz.idx===quiz.arr.length-1&&d>0){location.hash=`course/${quiz.id}`;return;}quiz.idx=Math.max(0,Math.min(quiz.arr.length-1,quiz.idx+d));let s={id:quiz.id,mode:quiz.mode,ids:quiz.arr.map(x=>x.id),idx:quiz.idx};sessionStorage.setItem('mb_quiz',JSON.stringify(s));drawQ();};
window.bookmark=id=>{let p=prog(quiz.id);p.bookmarks[id]=!p.bookmarks[id];if(!p.bookmarks[id])delete p.bookmarks[id];store.set('mb_'+quiz.id,p);drawQ();};
function stats(){let rows=courses.map(c=>{let p=prog(c.id),g=Object.keys(p.correct).length,ok=Object.values(p.correct).filter(Boolean).length;return `<div class="stat"><span>${c.icon} ${c.title}</span><b>${g?Math.round(ok/g*100):0}%</b><small class="tiny">${g}/${c.count} 채점</small></div>`}).join('');shell(`<div class="top"><div class="brand"><h1>학습 통계</h1><p>기기 안에 자동 저장된 기록</p></div><a class="btn" href="#">홈</a></div><div class="stats">${rows}</div>`);}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
async function render(){if(route.view==='home')return home();if(route.view==='course')return course(route.id);if(route.view==='quiz')return quizView(route.id,route.mode);if(route.view==='stats')return stats();home();}
init();
